name: Sync Fork

on:
  schedule:
    - cron: '0 */1 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          personal_token: ${{ secrets.SYNC_FORK_PAT }}
          github_token: ${{ github.token }}
          auto_approve: true
          owner: unifreq
          base: master
          head: master
          merge_method: squash
          ignore_fail: false

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0